openapi: 3.0.0
info:
  title: Shop API
  version: 1.0.0

servers:
  - url: 'http://shop.com'

paths:
  /account/create:
    post:
      operationId: createAccount
      summary: Account creation endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: Account created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Incorrect or incomplete data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    get:
      operationId: getSignupPage
      summary: Retrieve the account creation page
      responses:
        '200':
          description: Returns the account creation page with form fields
          content:
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/Account'
  /login:
    get:
      operationId: loginUser
      summary: User login
      responses:
        '200':
          description: Successful login

components:
  schemas:
    Account:
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        confirm_password:
          type: string
          format: password
        address:
          type: string
